variables:
  CI_SERVER_URL: http://makebe-gitlab
stages:
  - build
  - deploy
  - deploy-prod

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0.416
  script:
    - dotnet clean
    - rm -rf published
    - dotnet publish api.makebe.agenda/api.makebe.agenda.csproj -c Release -o published
    - ls published | grep lib.makebe.Applications.dll

  tags:
    - docker
  artifacts:
    paths:
      - published/
  cache:
    paths:
      - ~/.nuget/packages   

deploy:
  stage: deploy
  image: docker:stable 
  before_script:
    - apt-get update && apt-get install -y rsync 
  script:
    - docker pull api-agenda:latest || true  
    - docker build -t api-agenda:latest . 
    - docker stop makebe-agenda || true  
    - docker rm makebe-agenda || true     
    - docker run -d --name makebe-agenda -p 82:80 
       --dns 8.8.8.8 --dns 8.8.4.4
       -v /mnt/arquivos/makebeserver/dockercompose/app-agenda/appsettings.json:/App/appsettings.json 
       -v /home/makebe-user/Imagens:/App/uploads 
       -v /home/makebe-user/Imagens/HTML:/App/uploads/HTML 
       -v /etc/localtime:/etc/localtime:ro api-agenda:latest
       -v /mnt/arquivos/makebeserver/dockercompose/App/data_protection_keys:/home/makebe-user/.aspnet/DataProtection-Keys
    - docker network connect dockercompose_makebe-rede makebe-agenda 
  tags: [docker]
  only: [main]
  when: manual

deploy-prod:
  stage: deploy-prod
  image: alpine:latest
  needs: [build]

  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$AWS_DEPLOY_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H "$AWS_HOST" >> ~/.ssh/known_hosts

  script:
    - ssh "$AWS_USER@$AWS_HOST" "mkdir -p '$AWS_API_PATH'"
    - ssh "$AWS_USER@$AWS_HOST" "rm -rf '$AWS_API_PATH'/*"
    - tar -C published -cf - . | ssh "$AWS_USER@$AWS_HOST" "tar -C '$AWS_API_PATH' -xf -"
    - scp Dockerfile.published "$AWS_USER@$AWS_HOST:$AWS_API_PATH/Dockerfile"

    - ssh "$AWS_USER@$AWS_HOST" "cd '$AWS_API_PATH' && docker build --no-cache -t api-makebe-agenda:latest ."
    - ssh "$AWS_USER@$AWS_HOST" "docker stop api-makebe-agenda 2>/dev/null || true"
    - ssh "$AWS_USER@$AWS_HOST" "docker rm api-makebe-agenda 2>/dev/null || true"
    - ssh "$AWS_USER@$AWS_HOST" "docker run -d --name api-makebe-agenda --network makebe_makebe-rede -p 4001:80 -v /makebe/api/agenda/appsettings.json:/App/appsettings.json -v /makebe/pacotes/imagens:/App/imagens -v /etc/localtime:/etc/localtime:ro api-makebe-agenda:latest"
  tags: [docker]
  only: [main]
  when: manual
  environment:
    name: production
