variables:
  CI_SERVER_URL: http://makebe-gitlab
stages:
  - restore
  - build
  - deploy

restore:
  stage: restore
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet nuget locals all --clear  
    - dotnet restore --verbosity detailed
  tags:
    - docker  
  cache:
    paths:
      - ~/.nuget/packages  

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build 
    - dotnet publish -c Release -o published
  tags:
    - docker
  artifacts:
    paths:
      - published/
  cache:
    paths:
      - ~/.nuget/packages   

deploy:
  stage: deploy
  image: docker:stable 
  before_script:
    - apt-get update && apt-get install -y rsync 
  script:
    - docker pull api-agenda:latest || true  
    - docker build -t api-agenda:latest . 
    - docker stop makebe-agenda || true  
    - docker rm makebe-agenda || true     
    - docker run -d --name makebe-agenda -p 81:80 
       --dns 8.8.8.8 --dns 8.8.4.4
       -v /mnt/arquivos/makebeserver/dockercompose/app-agenda/appsettings.json:/App/appsettings.json 
       -v /home/makebe-user/Imagens:/App/uploads 
       -v /home/makebe-user/Imagens/HTML:/App/uploads/HTML 
       -v /etc/localtime:/etc/localtime:ro api-makebe:latest
       -v /mnt/arquivos/makebeserver/dockercompose/App/data_protection_keys:/home/makebe-user/.aspnet/DataProtection-Keys
    - docker network connect dockercompose_makebe-rede makebe-agenda 
  tags:
    - docker
  only:
    - main 