<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="lib.makebe.Applications" Version="2.0.0" />
    <PackageReference Include="lib.makebe.domain" Version="1.1.6" />
    <PackageReference Include="lib.makebe.Repository" Version="1.2.6" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api.makebe.agenda.applications\api.makebe.agenda.applications.csproj" />
    <ProjectReference Include="..\api.makebe.agenda.domain\api.makebe.agenda.domain.csproj" />
    <ProjectReference Include="..\api.makebe.agenda.infra.crosscutting.ioc\api.makebe.agenda.infra.crosscutting.ioc.csproj" />
    <ProjectReference Include="..\api.makebe.agenda.infra.crosscutting\api.makebe.agenda.infra.crosscutting.csproj" />
  </ItemGroup>

</Project>
